name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]


jobs:
  tests:
    name: Run tests
    uses: monicahq/workflows/.github/workflows/laravel.yml@v2
    with:
      php-versions: "['8.2']"
      connections: "['sqlite', 'mysql']"
      default-php-version: '8.2'
      default-connection: sqlite
      project: monicahq_version
      database_name: version
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  assets:
    name: Build assets
    uses: monicahq/workflows/.github/workflows/build_assets.yml@v2
    with:
      node-version: 18
