name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  tests:
    uses: monicahq/workflows/.github/workflows/laravel.yml@init
    with:
      php-version: ${{ matrix.php-version }}
      connection: ${{ matrix.connection }}
      coverage: ${{ matrix.connection == 'sqlite' && matrix.php-version == '8.2' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']
        connection: [sqlite, mysql]

  reporting:
    uses: monicahq/workflows/.github/workflows/reporting.yml@init
    with:
      project: monicahq_version
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: tests

  release:
    uses: monicahq/workflows/.github/workflows/release.yml@init
    secrets:
      GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
    needs: tests

  junit:
    uses: monicahq/workflows/.github/workflows/junit.yml@init
    needs: tests
